### ISSUE TITLE
can ncats-adme be run locally in commandline without calling API?

### ISSUE THREAD

**Issue by ravinpoudel** [ncats/ncats-adme#113]
Hi,
I am wondering if there is an option to run the ncats-adme model locally without calling for API. I have dockerized the tool, and exposed API to the port locally, then once api becomes available, I am running the model. IF there is way to run the model without going via the API, i think it will be much effiecient, computationally. 

Regards,
Ravin

**Comment by iwwwish** [comment]
Hi Ravin,

Sorry for the delayed response. At the moment, I think the only way the models can be called is via the API. This choice was probably made for good reasons (e.g., to be able to call the models from scripts). I recall you raised a similar issue (#95) in the past and I provided you a [sample script](https://gist.github.com/iwwwish/89ca830ca449a77c4595922224fe5d55) to make predictions from command line. Please feel free to modify the open source code to suit your needs.

One way I think you can boost the speed is to download the model files to your local disk and load them directly into your code or call them via command line. This way you bypass the API and can make predictions on a large batch of compounds. For the GCNN models, you could use the Chemprop's [command line option](https://github.com/chemprop/chemprop?tab=readme-ov-file#predicting) by pointing to the corresponding model checkpoints. Hope this helps.

Best,
Vishal

**Comment by iwwwish** [comment]
Please feel free to reopen if you have further questions. Thank you!
