### ISSUE TITLE
Cannot make cyp450 prediction

### ISSUE THREAD

**Issue by Frank-LIU-520** [ncats/ncats-adme#61]
When I try to make cyp450 prediction. It went collapse on my own computer.  I followed all the steps carefully and nothing went wrong. But still cannot precit cyp450 property. What should I do?

**Comment by iwwwish** [comment]
Hi Frank!

How are you running the program? If it is via `python app.py` command, could you provide the output from your terminal? Could you also provide me the operating system and memory details? These would help determine the exact issue.

Thanks,
Vishal
