### ISSUE TITLE
no information about redkit dependencies in ReadMe

### ISSUE THREAD

**Issue by Med16-11** [ncats/ncats-adme#81]
Hello maintainers! I am Medhavi Singh , an Outreachy applicant. After setting up the environment, when I tried running "python app.py"
I received following error.
![Screenshot from 2023-03-13 19-49-34](https://user-images.githubusercontent.com/78318301/224732984-7434e6c1-1ac1-47b1-821e-4285148c40cf.png)

I think it should be mentioned in the ReadMe that we need to install redkit before proceeding. This can be updated. Do let me know your thoughts. If you want I can create a PR for updated ReadMe.
Thank you!

**Comment by iwwwish** [comment]
Hi Medhavi! Thank you for reaching out. The anaconda [environment file](https://github.com/ncats/ncats-adme/blob/master/server/environment.yml) you used to set up the environment lists `rdkit` as one of the required packages. This means the package should be installed when you create the environment.

In your case, you may have created the environment successfully but haven't activated it before running `python3 app.py`. Could you activate the environment using the command `conda activate ./env` and then give it a try? From the screenshot, I see that you are still in your base environment when you tried to launch the application. Hope that helps.

Best,
Vishal

**Comment by Med16-11** [comment]
Hello @iwwwish ! Thanks for the quick response.
I tried following the steps that you have suggested but I am still receiving this another error.

![image](https://user-images.githubusercontent.com/78318301/224779290-b68899d6-9632-4e6c-8a57-32e97278ff56.png)

Can you suggest me how to resolve it? It would be very helpful.

**Comment by iwwwish** [comment]
Did you have any errors when you created the condo environment? If it went through fine, you should be able to activate the condo environment. Can you provide me the output of `condo env list`?

**Comment by Med16-11** [comment]
yup here it is!
![image](https://user-images.githubusercontent.com/78318301/224782763-1398c9cc-518d-4d9c-ad5b-07964eba6d89.png)

**Comment by iwwwish** [comment]
Looks the environment did not get installed otherwise it would show up in this list. Can you try creating the environment again? This time, please clone the development branch as this code contains the most recent updates. To clone development branch, use this command: `git clone --recursive -b development https://github.com/ncats/ncats-adme.git`. The rest of the instructions are same. Please keep me posted how it goes.

**Comment by Med16-11** [comment]
![image](https://user-images.githubusercontent.com/78318301/224902450-aa9c04a4-8ce7-49c0-9059-7d388c82b066.png)

I am not sure why I am not able to create the environment. Although I think their is some issues from my side.

**Comment by Med16-11** [comment]
![image](https://user-images.githubusercontent.com/78318301/224904958-379b695f-6f46-4b6f-81db-85f1d65df04e.png)

It's space related issue. Now I need to figure out how to solve it.
Also one thing I noticed is that I got this space error when I used the link provided by you in the discussion while when I was using the link in ReadMe it was not giving any space related error. Maybe this needs to be updated.

**Comment by iwwwish** [comment]
Hi again! Unfortunately, the app requires a fair amount of space to be
available on the disk. Further, after you successfully create the
environment and launch the app, it loads a lot of models into memory. Some
of these models are small in size but some of them are in the order of
gigabytes. Therefore, I would recommend you to use a machine with at least
8gb or 16gb RAM and over 15-20 gigabytes of empty space left on it. I will
add a note to the README about the memory and space requirements.

Hope this helps!

Best,
Vishal

**Comment by Med16-11** [comment]
Definitely, thank you so much for your valuable feedback.
