### ISSUE TITLE
HLM Model File

### ISSUE THREAD

**Issue by GemmaTuron** [ncats/ncats-adme#84]
Hello @iwwwish !

Thanks for sharing this resource with the community, it is a great implementation! I am the CEO of Ersilia a non profit organisation working to support infectious disease research in LMIC. 
I have successfully installed all models and run them in my system, but the HLM model seems to be corrupt (I am downloading the files from the link in the development branch) 
The model is not either available for online inference through the ADME-NCATS website. 
Could you check the current model and let me know if there is an updated version?

Many thanks

**Comment by GemmaTuron** [comment]
In line 21 of the app file, the import of HLM is still commented (https://github.com/ncats/ncats-adme/blob/development/server/app.py)
Also, I was trying to run the model independently but we've realized it uses the RLM predictions as additional features, hence the RLM model is also needed. 
So, it works for us now, thanks! Maybe documentation explaining why the HLM model is using RLM would be beneficial, is there a publication describing the HLM dataset? The publication linked in the website refers to the HCL dataset.

Thanks!

**Comment by iwwwish** [comment]
Hi Gemma! Thanks so much for your interest in our work. I can see that you already cloned the development branch which is the most recently updated version of the application. We did not make the HLM model public yet as we are waiting for the corresponding publication to be out. In short, the reason HLM model uses RLM predictions is the string correlation between the two endpoints. Although inter-species differences exist, our data indicates good correlation between the two assays. You will find more details on this in the upcoming paper. Hope this helps.

Best,
Vishal
