### ISSUE TITLE
Option to run it locally as command line without browser

### ISSUE THREAD

**Issue by ravinpoudel** [ncats/ncats-adme#95]
Hi, 

I am interested in using the tool as a command line. Wondering if this feature will/can be made available?

OR any suggestion to running as a command line using the current version of the tools?

Regards,
Ravin

**Comment by iwwwish** [comment]
Hi Ravin,

Thank you for your interest in this work. We have an [API](https://opendata.ncats.nih.gov/adme/api) that can be used behind a simple command line utility. I wrote a very basic version that is [available here](https://gist.github.com/iwwwish/89ca830ca449a77c4595922224fe5d55). Please feel free to tweak it as needed (e.g., for batch predictions or CSV file input).

Usage:

```
python adme_api.py -s 'OC(COC1=C2C=CC=CC2=CC=C1)CNC(C)C' -m rlm
```

Output:

```
Prediction (Probability): 1 (0.71)
Prediction Label: unstable
Tanimoto Similarity (to nearest neighbor in training set): 0.41
```

Hope this helps.

Best,
Vishal

**Comment by iwwwish** [comment]
Provided a simple working example of a command line wrapper that uses the API.
