### ISSUE TITLE
ModuleNotFoundError: No module named 'predictors.rlm'

### ISSUE THREAD

**Issue by Aml-Hassan-Abd-El-hamid** [ncats/ncats-adme#99]
Hi there,

I'm new to this repo, I followed the installation instructions from the readme and then I tried to run the command `python app.py` in the server folder but I got the following error:
```
(/home/aml/ncats-adme/server/env) aml@aml-HP-ZBook-15-G3:~/ncats-adme/server$ python app.py
Traceback (most recent call last):
  File "app.py", line 20, in <module>
    from predictors.rlm.rlm_predictor import RLMPredictior
ModuleNotFoundError: No module named 'predictors.rlm'

```

Can you please help me with that?

**Comment by iwwwish** [comment]
Hi,

Could you provide a few more details? Were you able to install and activate the anaconda environment without any issues? I don't understand why it tries to import `predictors.rlm` as a module. The predictors are all available in the folder `ncats-adme/server/predictors` and they should be imported without any issues.

**Comment by Aml-Hassan-Abd-El-hamid** [comment]
sorry for the late replay, I deleted the first environment and created a new one and it worked this time, I don't really know what was the issue with the initial installation but I think it was mostly a network issue that missed up the first installation.
